// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGN2fSBAab6j6pfc1cBQhCMR_RBHzWjhc',
    appId: '1:768294231240:web:71e5635fb7ea39d6b759fd',
    messagingSenderId: '768294231240',
    projectId: 'food-order-app-9ca99',
    authDomain: 'food-order-app-9ca99.firebaseapp.com',
    databaseURL: 'https://food-order-app-9ca99-default-rtdb.firebaseio.com',
    storageBucket: 'food-order-app-9ca99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpjrI84P0Gdfl27MVFcJwutSUcFI9KVIQ',
    appId: '1:768294231240:android:c86fec2d53bbd31ab759fd',
    messagingSenderId: '768294231240',
    projectId: 'food-order-app-9ca99',
    databaseURL: 'https://food-order-app-9ca99-default-rtdb.firebaseio.com',
    storageBucket: 'food-order-app-9ca99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5JyGDKZhrhs5S1v5w478Y3mT6XnqSWuU',
    appId: '1:768294231240:ios:7602deae558bba69b759fd',
    messagingSenderId: '768294231240',
    projectId: 'food-order-app-9ca99',
    databaseURL: 'https://food-order-app-9ca99-default-rtdb.firebaseio.com',
    storageBucket: 'food-order-app-9ca99.appspot.com',
    iosClientId: '768294231240-httqhkl6csn9uqpm3id51m0koac52d79.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5JyGDKZhrhs5S1v5w478Y3mT6XnqSWuU',
    appId: '1:768294231240:ios:7602deae558bba69b759fd',
    messagingSenderId: '768294231240',
    projectId: 'food-order-app-9ca99',
    databaseURL: 'https://food-order-app-9ca99-default-rtdb.firebaseio.com',
    storageBucket: 'food-order-app-9ca99.appspot.com',
    iosClientId: '768294231240-httqhkl6csn9uqpm3id51m0koac52d79.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
